app = "myapp"
primary_region = "cdg"

[env]
  PORT = "3000"
[build]
  dockerfile = "Dockerfile"
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0